# Generated by APEBind. Do not edit directly.
from __future__ import annotations

import json
from pathlib import Path

from ._runtime import APEClient


_OPERATIONS = json.loads(r'''{
  "share": {
    "command_path": [
      "share"
    ],
    "execution": "persistent",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "json_file",
      "field": "link",
      "option_flag": "--json",
      "ready_timeout_seconds": 20.0,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "share"
        ],
        "token": "share",
        "positionals": [
          {
            "api_name": "paths",
            "required": false,
            "multiple": true
          }
        ],
        "options": [
          {
            "flags": [
              "--version"
            ],
            "primary_flag": "--version",
            "api_name": "version",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--cli"
            ],
            "primary_flag": "--cli",
            "api_name": "cli",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--log-level"
            ],
            "primary_flag": "--log-level",
            "api_name": "log_level",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--proxy"
            ],
            "primary_flag": "--proxy",
            "api_name": "proxy",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--hook"
            ],
            "primary_flag": "--hook",
            "api_name": "hook",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--enable-reporting"
            ],
            "primary_flag": "--enable-reporting",
            "api_name": "enable_reporting",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--name",
              "-n"
            ],
            "primary_flag": "--name",
            "api_name": "name",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--exclude"
            ],
            "primary_flag": "--exclude",
            "api_name": "exclude",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--json"
            ],
            "primary_flag": "--json",
            "api_name": "json",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": true
          },
          {
            "flags": [
              "--upload"
            ],
            "primary_flag": "--upload",
            "api_name": "upload",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": true,
            "runtime_owned": false
          },
          {
            "flags": [
              "--resume"
            ],
            "primary_flag": "--resume",
            "api_name": "resume",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pause"
            ],
            "primary_flag": "--pause",
            "api_name": "pause",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--yes"
            ],
            "primary_flag": "--yes",
            "api_name": "yes",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--legacy-link"
            ],
            "primary_flag": "--legacy-link",
            "api_name": "legacy_link",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--max-downloads"
            ],
            "primary_flag": "--max-downloads",
            "api_name": "max_downloads",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--timeout"
            ],
            "primary_flag": "--timeout",
            "api_name": "timeout",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--port"
            ],
            "primary_flag": "--port",
            "api_name": "port",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--auth-user"
            ],
            "primary_flag": "--auth-user",
            "api_name": "auth_user",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--auth-password"
            ],
            "primary_flag": "--auth-password",
            "api_name": "auth_password",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-auth"
            ],
            "primary_flag": "--recipient-auth",
            "api_name": "recipient_auth",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pickup-code"
            ],
            "primary_flag": "--pickup-code",
            "api_name": "pickup_code",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-public-key"
            ],
            "primary_flag": "--recipient-public-key",
            "api_name": "recipient_public_key",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-email"
            ],
            "primary_flag": "--recipient-email",
            "api_name": "recipient_email",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-otp-api-base"
            ],
            "primary_flag": "--recipient-otp-api-base",
            "api_name": "recipient_otp_api_base",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--force-relay"
            ],
            "primary_flag": "--force-relay",
            "api_name": "force_relay",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--e2ee"
            ],
            "primary_flag": "--e2ee",
            "api_name": "e2ee",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--invite"
            ],
            "primary_flag": "--invite",
            "api_name": "invite",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--qr"
            ],
            "primary_flag": "--qr",
            "api_name": "qr",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": true,
            "runtime_owned": false
          },
          {
            "flags": [
              "--disable-clipboard"
            ],
            "primary_flag": "--disable-clipboard",
            "api_name": "disable_clipboard",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--vfs"
            ],
            "primary_flag": "--vfs",
            "api_name": "vfs",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--stdin-cache"
            ],
            "primary_flag": "--stdin-cache",
            "api_name": "stdin_cache",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--background"
            ],
            "primary_flag": "--background",
            "api_name": "background",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--foreground"
            ],
            "primary_flag": "--foreground",
            "api_name": "foreground",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--alias"
            ],
            "primary_flag": "--alias",
            "api_name": "alias",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--receipt"
            ],
            "primary_flag": "--receipt",
            "api_name": "receipt",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": true,
            "runtime_owned": false
          },
          {
            "flags": [
              "--receipt-confirm"
            ],
            "primary_flag": "--receipt-confirm",
            "api_name": "receipt_confirm",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": true,
            "runtime_owned": false
          },
          {
            "flags": [
              "--preferred-tunnel"
            ],
            "primary_flag": "--preferred-tunnel",
            "api_name": "preferred_tunnel",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  },
  "download": {
    "command_path": [
      "download"
    ],
    "execution": "persistent",
    "process": {
      "timeout_seconds": null
    },
    "result": {
      "format": "command",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "download"
        ],
        "token": "download",
        "positionals": [
          {
            "api_name": "url",
            "required": true,
            "multiple": false
          }
        ],
        "options": [
          {
            "flags": [
              "--version"
            ],
            "primary_flag": "--version",
            "api_name": "version",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--cli"
            ],
            "primary_flag": "--cli",
            "api_name": "cli",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--log-level"
            ],
            "primary_flag": "--log-level",
            "api_name": "log_level",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--proxy"
            ],
            "primary_flag": "--proxy",
            "api_name": "proxy",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--hook"
            ],
            "primary_flag": "--hook",
            "api_name": "hook",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--enable-reporting"
            ],
            "primary_flag": "--enable-reporting",
            "api_name": "enable_reporting",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--output",
              "-o"
            ],
            "primary_flag": "--output",
            "api_name": "output_path",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--resume"
            ],
            "primary_flag": "--resume",
            "api_name": "resume",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--auth-user"
            ],
            "primary_flag": "--auth-user",
            "api_name": "auth_user",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--auth-password"
            ],
            "primary_flag": "--auth-password",
            "api_name": "auth_password",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-auth"
            ],
            "primary_flag": "--recipient-auth",
            "api_name": "recipient_auth",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pickup-code"
            ],
            "primary_flag": "--pickup-code",
            "api_name": "pickup_code",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-private-key"
            ],
            "primary_flag": "--recipient-private-key",
            "api_name": "recipient_private_key",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--stdout"
            ],
            "primary_flag": "--stdout",
            "api_name": "stdout",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  },
  "keygen": {
    "command_path": [
      "keygen"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": 60.0
    },
    "result": {
      "format": "command",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "keygen"
        ],
        "token": "keygen",
        "positionals": [],
        "options": [
          {
            "flags": [
              "--version"
            ],
            "primary_flag": "--version",
            "api_name": "version",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--cli"
            ],
            "primary_flag": "--cli",
            "api_name": "cli",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--log-level"
            ],
            "primary_flag": "--log-level",
            "api_name": "log_level",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--proxy"
            ],
            "primary_flag": "--proxy",
            "api_name": "proxy",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--hook"
            ],
            "primary_flag": "--hook",
            "api_name": "hook",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--enable-reporting"
            ],
            "primary_flag": "--enable-reporting",
            "api_name": "enable_reporting",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--name"
            ],
            "primary_flag": "--name",
            "api_name": "name",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--share"
            ],
            "primary_flag": "--share",
            "api_name": "share",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--json"
            ],
            "primary_flag": "--json",
            "api_name": "json",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-auth"
            ],
            "primary_flag": "--recipient-auth",
            "api_name": "recipient_auth",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pickup-code"
            ],
            "primary_flag": "--pickup-code",
            "api_name": "pickup_code",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-public-key"
            ],
            "primary_flag": "--recipient-public-key",
            "api_name": "recipient_public_key",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-email"
            ],
            "primary_flag": "--recipient-email",
            "api_name": "recipient_email",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-otp-api-base"
            ],
            "primary_flag": "--recipient-otp-api-base",
            "api_name": "recipient_otp_api_base",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  },
  "version": {
    "command_path": [
      "share"
    ],
    "execution": "oneshot",
    "process": {
      "timeout_seconds": 30.0
    },
    "result": {
      "format": "text",
      "field": null,
      "option_flag": null,
      "ready_timeout_seconds": null,
      "strip": true
    },
    "levels": [
      {
        "path": [],
        "token": null,
        "positionals": [],
        "options": []
      },
      {
        "path": [
          "share"
        ],
        "token": "share",
        "positionals": [
          {
            "api_name": "paths",
            "required": false,
            "multiple": true
          }
        ],
        "options": [
          {
            "flags": [
              "--version"
            ],
            "primary_flag": "--version",
            "api_name": "version",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--cli"
            ],
            "primary_flag": "--cli",
            "api_name": "cli",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--log-level"
            ],
            "primary_flag": "--log-level",
            "api_name": "log_level",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--proxy"
            ],
            "primary_flag": "--proxy",
            "api_name": "proxy",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--hook"
            ],
            "primary_flag": "--hook",
            "api_name": "hook",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--enable-reporting"
            ],
            "primary_flag": "--enable-reporting",
            "api_name": "enable_reporting",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--name",
              "-n"
            ],
            "primary_flag": "--name",
            "api_name": "name",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--exclude"
            ],
            "primary_flag": "--exclude",
            "api_name": "exclude",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--json"
            ],
            "primary_flag": "--json",
            "api_name": "json",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--upload"
            ],
            "primary_flag": "--upload",
            "api_name": "upload",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": true,
            "runtime_owned": false
          },
          {
            "flags": [
              "--resume"
            ],
            "primary_flag": "--resume",
            "api_name": "resume",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pause"
            ],
            "primary_flag": "--pause",
            "api_name": "pause",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--yes"
            ],
            "primary_flag": "--yes",
            "api_name": "yes",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--legacy-link"
            ],
            "primary_flag": "--legacy-link",
            "api_name": "legacy_link",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--max-downloads"
            ],
            "primary_flag": "--max-downloads",
            "api_name": "max_downloads",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--timeout"
            ],
            "primary_flag": "--timeout",
            "api_name": "timeout",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--port"
            ],
            "primary_flag": "--port",
            "api_name": "port",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--auth-user"
            ],
            "primary_flag": "--auth-user",
            "api_name": "auth_user",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--auth-password"
            ],
            "primary_flag": "--auth-password",
            "api_name": "auth_password",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-auth"
            ],
            "primary_flag": "--recipient-auth",
            "api_name": "recipient_auth",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--pickup-code"
            ],
            "primary_flag": "--pickup-code",
            "api_name": "pickup_code",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-public-key"
            ],
            "primary_flag": "--recipient-public-key",
            "api_name": "recipient_public_key",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-email"
            ],
            "primary_flag": "--recipient-email",
            "api_name": "recipient_email",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--recipient-otp-api-base"
            ],
            "primary_flag": "--recipient-otp-api-base",
            "api_name": "recipient_otp_api_base",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--force-relay"
            ],
            "primary_flag": "--force-relay",
            "api_name": "force_relay",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--e2ee"
            ],
            "primary_flag": "--e2ee",
            "api_name": "e2ee",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--invite"
            ],
            "primary_flag": "--invite",
            "api_name": "invite",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--qr"
            ],
            "primary_flag": "--qr",
            "api_name": "qr",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": true,
            "runtime_owned": false
          },
          {
            "flags": [
              "--disable-clipboard"
            ],
            "primary_flag": "--disable-clipboard",
            "api_name": "disable_clipboard",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--vfs"
            ],
            "primary_flag": "--vfs",
            "api_name": "vfs",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--stdin-cache"
            ],
            "primary_flag": "--stdin-cache",
            "api_name": "stdin_cache",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--background"
            ],
            "primary_flag": "--background",
            "api_name": "background",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--foreground"
            ],
            "primary_flag": "--foreground",
            "api_name": "foreground",
            "boolean": true,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--alias"
            ],
            "primary_flag": "--alias",
            "api_name": "alias",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          },
          {
            "flags": [
              "--receipt"
            ],
            "primary_flag": "--receipt",
            "api_name": "receipt",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": true,
            "runtime_owned": false
          },
          {
            "flags": [
              "--receipt-confirm"
            ],
            "primary_flag": "--receipt-confirm",
            "api_name": "receipt_confirm",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": true,
            "runtime_owned": false
          },
          {
            "flags": [
              "--preferred-tunnel"
            ],
            "primary_flag": "--preferred-tunnel",
            "api_name": "preferred_tunnel",
            "boolean": false,
            "required": false,
            "multiple": false,
            "value_optional": false,
            "runtime_owned": false
          }
        ]
      }
    ]
  }
}''')
_RUNTIME = json.loads(r'''{
  "env_unset": [
    "PYTHONHOME",
    "PYTHONPATH",
    "PYTHONSTARTUP",
    "PYTHONDONTWRITEBYTECODE",
    "PYAPP"
  ]
}''')
_CLIENT = APEClient(
    Path(__file__).with_name('bin') / 'ffl.com',
    _OPERATIONS,
    _RUNTIME,
)


def share(
    paths=None,
    version=False,
    cli=False,
    log_level=None,
    proxy=None,
    hook=None,
    enable_reporting=False,
    name=None,
    exclude=None,
    upload=None,
    resume=False,
    pause=None,
    yes=False,
    legacy_link=None,
    max_downloads=None,
    timeout=None,
    port=None,
    auth_user=None,
    auth_password=None,
    recipient_auth=None,
    pickup_code=None,
    recipient_public_key=None,
    recipient_email=None,
    recipient_otp_api_base=None,
    force_relay=False,
    e2ee=False,
    invite=False,
    qr=None,
    disable_clipboard=False,
    vfs=False,
    stdin_cache=None,
    background=False,
    foreground=False,
    alias=None,
    receipt=None,
    receipt_confirm=None,
    preferred_tunnel=None,
    stdin=None,
    _apebind_capture_stdout=True,
):
    return _CLIENT.invoke(
        'share',
        {
            'paths': paths,
            'version': version,
            'cli': cli,
            'log_level': log_level,
            'proxy': proxy,
            'hook': hook,
            'enable_reporting': enable_reporting,
            'name': name,
            'exclude': exclude,
            'upload': upload,
            'resume': resume,
            'pause': pause,
            'yes': yes,
            'legacy_link': legacy_link,
            'max_downloads': max_downloads,
            'timeout': timeout,
            'port': port,
            'auth_user': auth_user,
            'auth_password': auth_password,
            'recipient_auth': recipient_auth,
            'pickup_code': pickup_code,
            'recipient_public_key': recipient_public_key,
            'recipient_email': recipient_email,
            'recipient_otp_api_base': recipient_otp_api_base,
            'force_relay': force_relay,
            'e2ee': e2ee,
            'invite': invite,
            'qr': qr,
            'disable_clipboard': disable_clipboard,
            'vfs': vfs,
            'stdin_cache': stdin_cache,
            'background': background,
            'foreground': foreground,
            'alias': alias,
            'receipt': receipt,
            'receipt_confirm': receipt_confirm,
            'preferred_tunnel': preferred_tunnel,
            'stdin': stdin,
            '_apebind_capture_stdout': _apebind_capture_stdout,
        },
    )


def download(
    url,
    version=False,
    cli=False,
    log_level=None,
    proxy=None,
    hook=None,
    enable_reporting=False,
    output_path=None,
    resume=False,
    auth_user=None,
    auth_password=None,
    recipient_auth=None,
    pickup_code=None,
    recipient_private_key=None,
    stdout=False,
    stdin=None,
    _apebind_capture_stdout=True,
):
    return _CLIENT.invoke(
        'download',
        {
            'url': url,
            'version': version,
            'cli': cli,
            'log_level': log_level,
            'proxy': proxy,
            'hook': hook,
            'enable_reporting': enable_reporting,
            'output_path': output_path,
            'resume': resume,
            'auth_user': auth_user,
            'auth_password': auth_password,
            'recipient_auth': recipient_auth,
            'pickup_code': pickup_code,
            'recipient_private_key': recipient_private_key,
            'stdout': stdout,
            'stdin': stdin,
            '_apebind_capture_stdout': _apebind_capture_stdout,
        },
    )


def keygen(
    version=False,
    cli=False,
    log_level=None,
    proxy=None,
    hook=None,
    enable_reporting=False,
    name=None,
    share=False,
    json=None,
    recipient_auth=None,
    pickup_code=None,
    recipient_public_key=None,
    recipient_email=None,
    recipient_otp_api_base=None,
):
    return _CLIENT.invoke(
        'keygen',
        {
            'version': version,
            'cli': cli,
            'log_level': log_level,
            'proxy': proxy,
            'hook': hook,
            'enable_reporting': enable_reporting,
            'name': name,
            'share': share,
            'json': json,
            'recipient_auth': recipient_auth,
            'pickup_code': pickup_code,
            'recipient_public_key': recipient_public_key,
            'recipient_email': recipient_email,
            'recipient_otp_api_base': recipient_otp_api_base,
        },
    )


def version(
    paths=None,
    version=False,
    cli=False,
    log_level=None,
    proxy=None,
    hook=None,
    enable_reporting=False,
    name=None,
    exclude=None,
    json=None,
    upload=None,
    resume=False,
    pause=None,
    yes=False,
    legacy_link=None,
    max_downloads=None,
    timeout=None,
    port=None,
    auth_user=None,
    auth_password=None,
    recipient_auth=None,
    pickup_code=None,
    recipient_public_key=None,
    recipient_email=None,
    recipient_otp_api_base=None,
    force_relay=False,
    e2ee=False,
    invite=False,
    qr=None,
    disable_clipboard=False,
    vfs=False,
    stdin_cache=None,
    background=False,
    foreground=False,
    alias=None,
    receipt=None,
    receipt_confirm=None,
    preferred_tunnel=None,
):
    return _CLIENT.invoke(
        'version',
        {
            'paths': paths,
            'version': version,
            'cli': cli,
            'log_level': log_level,
            'proxy': proxy,
            'hook': hook,
            'enable_reporting': enable_reporting,
            'name': name,
            'exclude': exclude,
            'json': json,
            'upload': upload,
            'resume': resume,
            'pause': pause,
            'yes': yes,
            'legacy_link': legacy_link,
            'max_downloads': max_downloads,
            'timeout': timeout,
            'port': port,
            'auth_user': auth_user,
            'auth_password': auth_password,
            'recipient_auth': recipient_auth,
            'pickup_code': pickup_code,
            'recipient_public_key': recipient_public_key,
            'recipient_email': recipient_email,
            'recipient_otp_api_base': recipient_otp_api_base,
            'force_relay': force_relay,
            'e2ee': e2ee,
            'invite': invite,
            'qr': qr,
            'disable_clipboard': disable_clipboard,
            'vfs': vfs,
            'stdin_cache': stdin_cache,
            'background': background,
            'foreground': foreground,
            'alias': alias,
            'receipt': receipt,
            'receipt_confirm': receipt_confirm,
            'preferred_tunnel': preferred_tunnel,
        },
    )


def raw(arguments: list[str], persistent: bool = False):
    return _CLIENT.raw(arguments, persistent=persistent)
